name: The K Experience
favicon: null
layout_spectrum: 0.7730121132917702
typography_spectrum: 0.46973169688135386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#ffffff'
    - '#004a00'
    - '#5d8d00'
    - '#adbc00'
  brandStrength: 0.5290168740320951
  lightness: 0.6751211127266288
  saturation: 0.43003123719245195
  rhythmicContrast: 0.0020449485164135695
purpose: []
